feat: Micrometerアダプタのデフォルトコンフィギュレーションを追加
nablarch/nablarch-default-configuration pull request #23
Opened 2020-08-31 06:32 UTC by opengl-8080

2020-09-02 05:43 UTC, backpaper0 requested changes

2020-09-02 05:43 UTC, backpaper0 commented on nablarch-main-default-configuration/src/main/resources/nablarch/integration/micrometer/micrometer.xml
> +  <config-file file="micrometer.properties" />
`micormeter.properties`は誰が用意するどういったファイルなんですか？

2020-09-02 07:54 UTC, opengl-8080 commented on nablarch-main-default-configuration/src/main/resources/nablarch/integration/micrometer/micrometer.xml
> +  <config-file file="micrometer.properties" />
アプリ側で用意する設定ファイルです。

```properties
# API キー
nablarch.micrometer.datadog.apiKey=XXXXXX
# push の間隔
nablarch.micrometer.datadog.step=5s
```

のようにレジストリごとの設定を記述します。

2020-09-02 21:26 UTC, backpaper0 commented on nablarch-main-default-configuration/src/main/resources/nablarch/integration/micrometer/micrometer.xml
> +  <config-file file="micrometer.properties" />
なるほど、わかりました。

このファイルがどういうものなのか、レビュアーにはわからないんですよね。
なのでプルリクエストの概要にでも説明があると良かったですね。
次からはレビュアーの状態を想像して、必要な情報があれば概要に記載するようにしてみてください。

2020-09-02 21:26 UTC, backpaper0 approved these changes

2020-09-03 00:35 UTC, opengl-8080 commented on nablarch-main-default-configuration/src/main/resources/nablarch/integration/micrometer/micrometer.xml
> +  <config-file file="micrometer.properties" />
配慮が足りていませんでした。申し訳ございません。
次からは修正内容を確認しやすいように概要に説明を記載します。
ご指摘ありがとうございます。

2020-09-08 04:14 UTC, merged